# Adapted from https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html
# This is for production environment.

# build stage
FROM node:lts as build-stage
WORKDIR /code
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:latest as production-stage
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /code/build /static